const menshirt = "/images/mens-shirt.svg";
const womenshirt = "/images/womens-dress.svg";
const groceries = "/images/grocery-basket.svg";
const homeoffice = "/images/sofa.svg";
const computers = "/images/computer.svg";
const power = "/images/power-generator.svg";
const electronics = "/images/electronics.svg";
const phones = "/images/mobile-phone.svg";
const kids = "/images/teddy-bear.svg";
const sports = "/images/sport-items.svg";
const healthbeauty = "/images/health-beauty.svg";
const mobileaccessories = "/images/mobile-accessories.svg";
const toysgames = "/images/toys-games.svg";

const valentineAd = "/images/large-fair-web-banner.svg";
const preciousGift = "/images/precious-gift.png";
const loveFair = "/images/love-fair.png";
const shoppingCart = "/images/shopping-bag.svg";

const girInHoodie = "/images/young-woman-in-hoodie.svg";

export const productCategories = [
  {
    id: 1,
    productName: "Men",
    productIcon: menshirt,
    link: `/category/${"beauty"}`,
  },
  {
    id: 2,
    productName: "Women",
    productIcon: womenshirt,
    link: `/category/${"beauty"}`,
  },
  {
    id: 3,
    productName: "Groceries",
    productIcon: groceries,
  },
  {
    id: 4,
    productName: "Home & Office",
    productIcon: homeoffice,
  },
  {
    id: 5,
    productName: "Computers",
    productIcon: computers,
    link: `/category/${"electronics"}`,
  },
  {
    id: 6,
    productName: "Power",
    productIcon: power,
    link: `/category/${"electronics"}`,
  },
  {
    id: 7,
    productName: "Electronics",
    productIcon: electronics,
    link: `/category/${"electronics"}`,
  },
  {
    id: 8,
    productName: "Phones",
    productIcon: phones,
    link: `/category/${"electronics"}`,
  },
  {
    id: 9,
    productName: "Kids",
    productIcon: kids,
    link: `/category${"/toys"}`,
  },
  {
    id: 10,
    productName: "Sports Items",
    productIcon: sports,
    link: `/category/${"toys"}`,
  },
  {
    id: 11,
    productName: "Health & Beauty",
    productIcon: healthbeauty,
    link: `/category/${"beauty"}`,
  },
  {
    id: 12,
    productName: "Mobile Accessories",
    productIcon: mobileaccessories,
    link: `/category/${"electronics"}`,
  },
  {
    id: 13,
    productName: "Toys & Games",
    productIcon: toysgames,
    link: `/category/${"toys"}`,
  },
];

export const productAds = [
  {
    id: 1,
    name: "Valentine's Special",
    image: valentineAd,
  },
  {
    id: 2,
    name: "Valentine's Special",
    image: preciousGift,
  },
  {
    id: 3,
    name: "Valentine's Special",
    image: valentineAd,
  },
];

export const heroCards = [
  {
    id: 1,
    image: loveFair,
    alt: "An Image of a lady sitting on the sofa while wearing hoodie",
  },
  {
    id: 2,
    image: girInHoodie,
    alt: "An Image of a lady sitting on the sofa while wearing hoodie",
    text: "Shop the latest",
    textDetails: "Electronics, fashion, home essentials, grocery all here.",
    shoppingCart: shoppingCart,
  },
  {
    id: 3,
    image: preciousGift,
    alt: "An Image of a lady sitting on the sofa while wearing hoodie",
  },
];

export const products = [
  // Electronics - Mobile Phones (10 products)
  {
    id: 1,
    name: "Samsung Galaxy Note 10 Plus",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1610792516307-ea5acd9c3b00?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2Ftc3VuZyUyMHBob25lfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N207,000.00",
    discountPrice: "N225,000.00",
    ratings: "3.5",
    noOfProductSold: "20",
  },
  {
    id: 2,
    name: "iPhone 14 Pro Max",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aXBob25lJTIwMTQlMjBwcm8lMjBtYXh8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    price: "N500,000.00",
    discountPrice: "N520,000.00",
    ratings: "4.8",
    noOfProductSold: "50",
  },
  {
    id: 3,
    name: "Google Pixel 7 Pro",
    brand: "Google",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1666919643134-d97687c1826c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Z29vZ2xlJTIwcGl4ZWwlMjA3JTIwcHJvfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N300,000.00",
    discountPrice: "N320,000.00",
    ratings: "4.6",
    noOfProductSold: "30",
  },
  {
    id: 4,
    name: "OnePlus 10 Pro",
    brand: "OnePlus",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1647427014769-706a64d7cbf9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b25lcGx1cyUyMDEwJTIwcHJvfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N280,000.00",
    discountPrice: "N300,000.00",
    ratings: "4.7",
    noOfProductSold: "25",
  },
  {
    id: 5,
    name: "Xiaomi Mi 12",
    brand: "Xiaomi",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1647427014769-706a64d7cbf9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b25lcGx1cyUyMDEwJTIwcHJvfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N200,000.00",
    discountPrice: "N220,000.00",
    ratings: "4.4",
    noOfProductSold: "22",
  },
  {
    id: 6,
    name: "Samsung Galaxy S22 Ultra",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1647427014769-706a64d7cbf9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b25lcGx1cyUyMDEwJTIwcHJvfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N400,000.00",
    discountPrice: "N420,000.00",
    ratings: "4.9",
    noOfProductSold: "40",
  },
  {
    id: 7,
    name: "iPhone SE (2022)",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1647427014769-706a64d7cbf9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b25lcGx1cyUyMDEwJTIwcHJvfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N150,000.00",
    discountPrice: "N170,000.00",
    ratings: "4.3",
    noOfProductSold: "18",
  },
  {
    id: 8,
    name: "Google Pixel 6a",
    brand: "Google",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1647427014769-706a64d7cbf9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b25lcGx1cyUyMDEwJTIwcHJvfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N180,000.00",
    discountPrice: "N200,000.00",
    ratings: "4.5",
    noOfProductSold: "28",
  },
  {
    id: 9,
    name: "OnePlus Nord 2",
    brand: "OnePlus",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1647427014769-706a64d7cbf9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b25lcGx1cyUyMDEwJTIwcHJvfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N220,000.00",
    discountPrice: "N240,000.00",
    ratings: "4.6",
    noOfProductSold: "35",
  },
  {
    id: 10,
    name: "Xiaomi Redmi Note 11",
    brand: "Xiaomi",
    category: "Electronics",
    subcategory: "Mobile Phones",
    image:
      "https://images.unsplash.com/photo-1647427014769-706a64d7cbf9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b25lcGx1cyUyMDEwJTIwcHJvfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N120,000.00",
    discountPrice: "N140,000.00",
    ratings: "4.2",
    noOfProductSold: "20",
  },

  // Electronics - TV & Video (10 products)
  {
    id: 11,
    name: "Samsung 55-inch 4K Smart TV",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c2Ftc3VuZyUyMHR2fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N300,000.00",
    discountPrice: "N320,000.00",
    ratings: "4.7",
    noOfProductSold: "15",
  },
  {
    id: 12,
    name: "LG 65-inch OLED Evo TV",
    brand: "LG",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGclMjB0dnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: "N500,000.00",
    discountPrice: "N550,000.00",
    ratings: "4.9",
    noOfProductSold: "20",
  },
  {
    id: 13,
    name: "Sony Bravia XR 77-inch OLED TV",
    brand: "Sony",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1586125182680-43e51d6a59ef?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNvbnklMjB0dnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: "N750,000.00",
    discountPrice: "N800,000.00",
    ratings: "4.8",
    noOfProductSold: "10",
  },
  {
    id: 14,
    name: "TCL 50-inch QLED TV",
    brand: "TCL",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8dGNsJTIwdnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: "N280,000.00",
    discountPrice: "N300,000.00",
    ratings: "4.6",
    noOfProductSold: "30",
  },
  {
    id: 15,
    name: "Hisense 58-inch ULED TV",
    brand: "Hisense",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1616443136967-0dfd0eb36eec?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGhpc2Vuc2UlMjB0dnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: "N350,000.00",
    discountPrice: "N370,000.00",
    ratings: "4.5",
    noOfProductSold: "25",
  },
  {
    id: 16,
    name: "Panasonic 65-inch 4K LED TV",
    brand: "Panasonic",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1569169332365-4cba327a6e0c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjN8fHR2JTIwbGVkJTIwNHh8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    price: "N450,000.00",
    discountPrice: "N480,000.00",
    ratings: "4.7",
    noOfProductSold: "18",
  },
  {
    id: 17,
    name: "Sharp 70-inch Aquos TV",
    brand: "Sharp",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1516192518150-0d8fee5425e3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fHR2JTIwYXF1b3N8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
    price: "N600,000.00",
    discountPrice: "N650,000.00",
    ratings: "4.8",
    noOfProductSold: "12",
  },
  {
    id: 18,
    name: "Vizio 55-inch M-Series TV",
    brand: "Vizio",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1558875212-efe031b62d1c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fHZpemlvJTIwdnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: "N320,000.00",
    discountPrice: "N350,000.00",
    ratings: "4.6",
    noOfProductSold: "22",
  },
  {
    id: 19,
    name: "Philips 50-inch Ambilight TV",
    brand: "Philips",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1604072363254-9d70d34fd678?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzB8fGxnbCUyMHR2JTIwYW1iaWxpZ2h0fGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
    price: "N280,000.00",
    discountPrice: "N310,000.00",
    ratings: "4.5",
    noOfProductSold: "14",
  },
  {
    id: 20,
    name: "Toshiba 55-inch Fire TV",
    brand: "Toshiba",
    category: "Electronics",
    subcategory: "TV & Video",
    image:
      "https://images.unsplash.com/photo-1598336001173-944fc87c5457?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzN8fHRvc2hpYmElMjB0dnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=500&q=60",
    price: "N310,000.00",
    discountPrice: "N340,000.00",
    ratings: "4.6",
    noOfProductSold: "19",
  },

  // Electronics - Fridge & Freezer (10 products)
  {
    id: 30,
    name: "LG Double Door Refrigerator",
    brand: "LG",
    category: "Electronics",
    subcategory: "Fridge & Freezer",
    image: "https://source.unsplash.com/500x500/?refrigerator",
    price: "N400,000.00",
    discountPrice: "N420,000.00",
    ratings: "4.6",
    noOfProductSold: "12",
  },
  {
    id: 31,
    name: "Samsung Smart TV 55 inch",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Television",
    image: "https://source.unsplash.com/500x500/?smart-tv",
    price: "N500,000.00",
    discountPrice: "N520,000.00",
    ratings: "4.8",
    noOfProductSold: "20",
  },
  {
    id: 32,
    name: "Sony Home Theater System",
    brand: "Sony",
    category: "Electronics",
    subcategory: "Audio",
    image: "https://source.unsplash.com/500x500/?home-theater",
    price: "N150,000.00",
    discountPrice: "N170,000.00",
    ratings: "4.5",
    noOfProductSold: "8",
  },
  {
    id: 33,
    name: "Apple MacBook Pro 16-inch",
    brand: "Apple",
    category: "Electronics",
    subcategory: "Laptop",
    image: "https://source.unsplash.com/500x500/?macbook",
    price: "N1,500,000.00",
    discountPrice: "N1,550,000.00",
    ratings: "4.9",
    noOfProductSold: "30",
  },
  {
    id: 34,
    name: "HP Envy x360 Laptop",
    brand: "HP",
    category: "Electronics",
    subcategory: "Laptop",
    image: "https://source.unsplash.com/500x500/?laptop",
    price: "N700,000.00",
    discountPrice: "N750,000.00",
    ratings: "4.7",
    noOfProductSold: "15",
  },
  {
    id: 35,
    name: "Bose Noise Cancelling Headphones",
    brand: "Bose",
    category: "Electronics",
    subcategory: "Headphones",
    image: "https://source.unsplash.com/500x500/?headphones",
    price: "N180,000.00",
    discountPrice: "N200,000.00",
    ratings: "4.8",
    noOfProductSold: "22",
  },
  {
    id: 36,
    name: "Canon EOS R6 Camera",
    brand: "Canon",
    category: "Electronics",
    subcategory: "Camera",
    image: "https://source.unsplash.com/500x500/?camera",
    price: "N900,000.00",
    discountPrice: "N950,000.00",
    ratings: "4.7",
    noOfProductSold: "10",
  },
  {
    id: 37,
    name: "Dell UltraSharp Monitor",
    brand: "Dell",
    category: "Electronics",
    subcategory: "Monitor",
    image: "https://source.unsplash.com/500x500/?monitor",
    price: "N300,000.00",
    discountPrice: "N320,000.00",
    ratings: "4.6",
    noOfProductSold: "18",
  },
  {
    id: 38,
    name: "Nike Air Max Sneakers",
    brand: "Nike",
    category: "Fashion",
    subcategory: "Shoes",
    image: "https://source.unsplash.com/500x500/?sneakers",
    price: "N80,000.00",
    discountPrice: "N90,000.00",
    ratings: "4.8",
    noOfProductSold: "40",
  },
  {
    id: 39,
    name: "Rolex Submariner Watch",
    brand: "Rolex",
    category: "Fashion",
    subcategory: "Watches",
    image: "https://source.unsplash.com/500x500/?watch",
    price: "N2,000,000.00",
    discountPrice: "N2,100,000.00",
    ratings: "4.9",
    noOfProductSold: "5",
  },

  // Electroonics - Kitchen Appliances

  {
    id: 41,
    name: "LG Double Door Refrigerator",
    brand: "LG",
    category: "Electronics",
    subcategory: "Refrigerators",
    image:
      "https://images.unsplash.com/photo-1615874959474-261469c61958?auto=format&fit=crop&w=500&q=60",
    price: "N400,000.00",
    discountPrice: "N420,000.00",
    ratings: "4.6",
    noOfProductSold: "12",
  },
  {
    id: 42,
    name: "Samsung Microwave Oven",
    brand: "Samsung",
    category: "Electronics",
    subcategory: "Microwaves",
    image:
      "https://images.unsplash.com/photo-1613564834360-1576b7e7c24b?auto=format&fit=crop&w=500&q=60",
    price: "N120,000.00",
    discountPrice: "N135,000.00",
    ratings: "4.7",
    noOfProductSold: "25",
  },
  {
    id: 43,
    name: "Panasonic 4-Burner Gas Cooker",
    brand: "Panasonic",
    category: "Electronics",
    subcategory: "Cookers",
    image:
      "https://images.unsplash.com/photo-1617634661841-68a8e8ebd51b?auto=format&fit=crop&w=500&q=60",
    price: "N150,000.00",
    discountPrice: "N165,000.00",
    ratings: "4.5",
    noOfProductSold: "18",
  },
  {
    id: 44,
    name: "Philips Air Fryer",
    brand: "Philips",
    category: "Electronics",
    subcategory: "Air Fryers",
    image:
      "https://images.unsplash.com/photo-1602285006030-57e12089c3b4?auto=format&fit=crop&w=500&q=60",
    price: "N85,000.00",
    discountPrice: "N95,000.00",
    ratings: "4.8",
    noOfProductSold: "30",
  },
  {
    id: 45,
    name: "Bosch Electric Kettle",
    brand: "Bosch",
    category: "Electronics",
    subcategory: "Kettles",
    image:
      "https://images.unsplash.com/photo-1617989829829-76768cfc2a43?auto=format&fit=crop&w=500&q=60",
    price: "N25,000.00",
    discountPrice: "N30,000.00",
    ratings: "4.4",
    noOfProductSold: "40",
  },
  {
    id: 46,
    name: "Nutribullet Blender",
    brand: "Nutribullet",
    category: "Electronics",
    subcategory: "Blenders",
    image:
      "https://images.unsplash.com/photo-1622202452170-44bda9f65c64?auto=format&fit=crop&w=500&q=60",
    price: "N45,000.00",
    discountPrice: "N50,000.00",
    ratings: "4.6",
    noOfProductSold: "22",
  },
  {
    id: 47,
    name: "Kenwood Food Processor",
    brand: "Kenwood",
    category: "Electronics",
    subcategory: "Food Processors",
    image:
      "https://images.unsplash.com/photo-1617634272385-5e05de9bdef6?auto=format&fit=crop&w=500&q=60",
    price: "N65,000.00",
    discountPrice: "N70,000.00",
    ratings: "4.7",
    noOfProductSold: "15",
  },
  {
    id: 48,
    name: "Hisense Chest Freezer",
    brand: "Hisense",
    category: "Electronics",
    subcategory: "Freezers",
    image:
      "https://images.unsplash.com/photo-1596901177920-0a3e3a6a1ec4?auto=format&fit=crop&w=500&q=60",
    price: "N210,000.00",
    discountPrice: "N225,000.00",
    ratings: "4.5",
    noOfProductSold: "10",
  },
  {
    id: 49,
    name: "Prestige Toaster",
    brand: "Prestige",
    category: "Electronics",
    subcategory: "Toasters",
    image:
      "https://images.unsplash.com/photo-1585602551062-2a3a91d19a6a?auto=format&fit=crop&w=500&q=60",
    price: "N20,000.00",
    discountPrice: "N25,000.00",
    ratings: "4.3",
    noOfProductSold: "35",
  },
  {
    id: 50,
    name: "LG Dishwasher",
    brand: "LG",
    category: "Kitchen Appliances",
    subcategory: "Dishwashers",
    image:
      "https://images.unsplash.com/photo-1596461404969-9ee7c4a83f65?auto=format&fit=crop&w=500&q=60",
    price: "N350,000.00",
    discountPrice: "N370,000.00",
    ratings: "4.7",
    noOfProductSold: "8",
  },

  //Beauty

  {
    id: 60,
    name: "Maybelline Fit Me Foundation",
    brand: "Maybelline",
    category: "beauty",
    subcategory: "Makeup",
    image:
      "https://images.unsplash.com/photo-1584949035913-2f52ecf2a7c2?auto=format&fit=crop&w=500&q=60",
    price: "N8,000.00",
    discountPrice: "N9,500.00",
    ratings: "4.7",
    noOfProductSold: "120",
  },
  {
    id: 61,
    name: "MAC Matte Lipstick",
    brand: "MAC",
    category: "beauty",
    subcategory: "Makeup",
    image:
      "https://images.unsplash.com/photo-1584949036477-9c86f18fef5b?auto=format&fit=crop&w=500&q=60",
    price: "N12,000.00",
    discountPrice: "N13,500.00",
    ratings: "4.8",
    noOfProductSold: "150",
  },
  {
    id: 62,
    name: "Nivea Body Lotion",
    brand: "Nivea",
    category: "beauty",
    subcategory: "Skincare",
    image:
      "https://images.unsplash.com/photo-1607611749438-4859c7b20f83?auto=format&fit=crop&w=500&q=60",
    price: "N3,500.00",
    discountPrice: "N4,000.00",
    ratings: "4.6",
    noOfProductSold: "200",
  },
  {
    id: 63,
    name: "CeraVe Foaming Facial Cleanser",
    brand: "CeraVe",
    category: "beauty",
    subcategory: "Skincare",
    image:
      "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=500&q=60",
    price: "N6,000.00",
    discountPrice: "N6,800.00",
    ratings: "4.9",
    noOfProductSold: "180",
  },
  {
    id: 64,
    name: "L'Oreal Paris Shampoo",
    brand: "L'Oreal Paris",
    category: "beauty",
    subcategory: "Haircare",
    image:
      "https://images.unsplash.com/photo-1591238372982-7c12d2d0f698?auto=format&fit=crop&w=500&q=60",
    price: "N2,800.00",
    discountPrice: "N3,200.00",
    ratings: "4.5",
    noOfProductSold: "250",
  },
  {
    id: 65,
    name: "Tresemme Conditioner",
    brand: "Tresemme",
    category: "beauty",
    subcategory: "Haircare",
    image:
      "https://images.unsplash.com/photo-1584268214172-dcbe15c1782f?auto=format&fit=crop&w=500&q=60",
    price: "N3,200.00",
    discountPrice: "N3,600.00",
    ratings: "4.7",
    noOfProductSold: "230",
  },
  {
    id: 66,
    name: "Zara Women Summer Dress",
    brand: "Zara",
    category: "beauty",
    subcategory: "Clothing",
    image:
      "https://images.unsplash.com/photo-1596755097985-7ebd97401cc0?auto=format&fit=crop&w=500&q=60",
    price: "N15,000.00",
    discountPrice: "N17,000.00",
    ratings: "4.5",
    noOfProductSold: "95",
  },
  {
    id: 67,
    name: "Nike Men's Running Shoes",
    brand: "Nike",
    category: "beauty",
    subcategory: "Clothing",
    image:
      "https://images.unsplash.com/photo-1598257006456-0c67f7dbe10b?auto=format&fit=crop&w=500&q=60",
    price: "N25,000.00",
    discountPrice: "N28,000.00",
    ratings: "4.8",
    noOfProductSold: "130",
  },
  {
    id: 68,
    name: "Rolex Gold Watch",
    brand: "Rolex",
    category: "beauty",
    subcategory: "Accessories",
    image:
      "https://images.unsplash.com/photo-1515121066213-7b7c4b0c8288?auto=format&fit=crop&w=500&q=60",
    price: "N2,500,000.00",
    discountPrice: "N2,700,000.00",
    ratings: "4.9",
    noOfProductSold: "15",
  },
  {
    id: 69,
    name: "Ray-Ban Aviator Sunglasses",
    brand: "Ray-Ban",
    category: "beauty",
    subcategory: "Accessories",
    image:
      "https://images.unsplash.com/photo-1610383964865-6a1e14200b21?auto=format&fit=crop&w=500&q=60",
    price: "N35,000.00",
    discountPrice: "N40,000.00",
    ratings: "4.7",
    noOfProductSold: "75",
  },

  //Toy & Games
  {
    id: "TG001",
    name: "LEGO Classic Creative Brick Box",
    brand: "LEGO",
    category: "toys",
    subcategory: "Building Toys",
    image: "https://images.lego.com/is/image/LEGO/11002_box1_v2?$main$",
    price: "N15,000.00",
    discountPrice: "N18,000.00",
    ratings: "4.8",
    noOfProductSold: "50",
  },
  {
    id: "TG002",
    name: "Barbie Dreamhouse",
    brand: "Barbie",
    category: "toys",
    subcategory: "Dolls & Accessories",
    image: "https://mattel.scene7.com/is/image/Mattel/GNH53_01?$oslarge$",
    price: "N45,000.00",
    discountPrice: "N50,000.00",
    ratings: "4.7",
    noOfProductSold: "35",
  },
  {
    id: "TG003",
    name: "Hot Wheels Ultimate Garage",
    brand: "Hot Wheels",
    category: "toys",
    subcategory: "Die-Cast Vehicles",
    image: "https://mattel.scene7.com/is/image/Mattel/GJL14_01?$oslarge$",
    price: "N25,000.00",
    discountPrice: "N28,000.00",
    ratings: "4.6",
    noOfProductSold: "40",
  },
  {
    id: "TG004",
    name: "Nerf N-Strike Elite Disruptor",
    brand: "Nerf",
    category: "toys",
    subcategory: "Outdoor Toys",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71PZzqJdLlL._AC_SL1500_.jpg",
    price: "N8,000.00",
    discountPrice: "N9,500.00",
    ratings: "4.5",
    noOfProductSold: "60",
  },
  {
    id: "TG005",
    name: "Monopoly Classic Board Game",
    brand: "Hasbro",
    category: "toys",
    subcategory: "Board Games",
    image: "https://m.media-amazon.com/images/I/81OYcW5QpLL._AC_SL1500_.jpg",
    price: "N12,000.00",
    discountPrice: "N14,000.00",
    ratings: "4.9",
    noOfProductSold: "45",
  },
  {
    id: "TG006",
    name: "Play-Doh Fun Factory Deluxe Set",
    brand: "Play-Doh",
    category: "toys",
    subcategory: "Creative Toys",
    image: "https://m.media-amazon.com/images/I/81Sjc4BPoQL._AC_SL1500_.jpg",
    price: "N6,000.00",
    discountPrice: "N7,000.00",
    ratings: "4.4",
    noOfProductSold: "55",
  },
  {
    id: "TG007",
    name: "Remote Control Drone with Camera",
    brand: "DJI",
    category: "toys",
    subcategory: "Remote Control Toys",
    image: "https://m.media-amazon.com/images/I/71mHDbvAroL._AC_SL1500_.jpg",
    price: "N30,000.00",
    discountPrice: "N35,000.00",
    ratings: "4.7",
    noOfProductSold: "20",
  },
  {
    id: "TG008",
    name: "Paw Patrol Marshall's Fire Truck",
    brand: "Paw Patrol",
    category: "toys",
    subcategory: "Action Figures",
    image: "https://m.media-amazon.com/images/I/81v3xd6XWzL._AC_SL1500_.jpg",
    price: "N10,000.00",
    discountPrice: "N12,000.00",
    ratings: "4.6",
    noOfProductSold: "30",
  },
  {
    id: "TG009",
    name: "Jenga Classic Game",
    brand: "Hasbro",
    category: "toys",
    subcategory: "Stacking Games",
    image: "https://m.media-amazon.com/images/I/91ANhPfI2CL._AC_SL1500_.jpg",
    price: "N7,000.00",
    discountPrice: "N8,000.00",
    ratings: "4.8",
    noOfProductSold: "65",
  },
  {
    id: "TG010",
    name: "Rubik's Cube 3x3",
    brand: "Rubik's",
    category: "toys",
    subcategory: "Puzzles",
    image: "https://m.media-amazon.com/images/I/61vV-Lw+TaL._AC_SL1000_.jpg",
    price: "N3,000.00",
    discountPrice: "N3,500.00",
    ratings: "4.7",
    noOfProductSold: "70",
  },
];

export const popularProducts = [
  {
    id: 1,
    image: "/images/computers&tablets.svg",
    name: "TV, Cell phone, Laptops",
    category: "Electronics",
    link: `/category/${"electronics"}`,
  },
  {
    id: 2,
    image: "/images/makeup-kits.svg",
    name: "Makeup,  hair, body lotion  ",
    category: "Health&Beauty",
    link: `/category/${"beauty"}`,
  },
  {
    id: 3,
    image: "/images/flower-basket.svg",
    name: "Rice, Yam, Chicken",
    category: "Groceries",
    link: "href/home/groceries",
  },
];

export const popularProductsSort = [
  {
    id: 1,
    image: "/images/american-man.svg",
    name: "Shirts, jeans, tees and more",
    category: "Men",
    link: `/category/${"beauty"}`,
  },
  {
    id: 2,
    image: "/images/fashionable-young-woman.svg",
    name: "Dresses, jewelries, hair and more ",
    category: "Women",
    link: `/category/${"beauty"}`,
  },
  {
    id: 3,
    image: "/images/american-kid.svg",
    name: "Sofa, decor, appliance and more",
    category: "Kids",
    link: `/category/${"toys"}`,
  },
  {
    id: 4,
    image: "/images/living-room.svg",
    name: "Sofa, decor, appliance and more",
    category: "Home",
    link: "./",
  },
];

export const menuFooter = [
  {
    title: "Fair",
    links: [
      { name: "About us", link: "/about-us" },
      { name: "Privacy policy", link: "/privacy-policy" },
      { name: "Feedback", link: "/feedback" },
      { name: "Press", link: "/press" },
      { name: "Legal", link: "/legal" },
      { name: "Careers", link: "/careers" },
    ],
  },
  {
    title: "Shop",
    links: [
      { name: "Categories", link: "/categories" },
      { name: "Deals", link: "/deals" },
      { name: "Trending", link: "/trending" },
      { name: "Buying guide", link: "/buying-guide" },
      { name: "Gift card", link: "/gift-card" },
      { name: "Create an account", link: "/create-account" },
    ],
  },
  {
    title: "Sell",
    links: [
      { name: "Start selling", link: "/start-selling" },
      { name: "How to sell", link: "/how-to-sell" },
      { name: "Getting paid", link: "/getting-paid" },
      { name: "Vendor app", link: "/vendor-app" },
    ],
  },
  {
    title: "Support",
    links: [
      { name: "Contact us", link: "/contact-us" },
      { name: "Help center", link: "/help-center" },
      { name: "Market place guidelines", link: "/marketplace-guidelines" },
      { name: "Buyer protection", link: "/buyer-protection" },
      { name: "Seller protection", link: "/seller-protection" },
      { name: "Refunds and returns", link: "/refunds-returns" },
    ],
  },
];
