const menshirt = '/images/mens-shirt.svg';
const womenshirt = '/images/womens-dress.svg';
const groceries = '/images/grocery-basket.svg';
const homeoffice = '/images/sofa.svg';
const computers = '/images/computer.svg';
const power = '/images/power-generator.svg';
const electronics = '/images/electronics.svg';
const phones = '/images/mobile-phone.svg';
const kids = '/images/teddy-bear.svg';
const sports = '/images/sport-items.svg';
const healthbeauty = '/images/health-beauty.svg';
const mobileaccessories = '/images/mobile-accessories.svg';
const toysgames = '/images/toys-games.svg';

const valentineAd = '/images/large-fair-web-banner.svg';
const preciousGift = '/images/precious-gift.png';
const YellowBox = '/images/YellowBox.svg';

const loveFair = '/images/love-fair.png';
const shoppingCart = '/images/shopping-bag.svg';
const happyMan =
  '/images/one-happy-young-african-american-man-sitting-on-hi(3).svg';

const girInHoodie = '/images/young-woman-in-hoodie.svg';

export const productCategories = [
  {
    id: 105,
    productName: 'Men',
    productIcon: menshirt,
    link: `/category/${'beauty'}`,
  },
  {
    id: 201,
    productName: 'Women',
    productIcon: womenshirt,
    link: `/category/${'beauty'}`,
  },
  {
    id: 300,
    productName: 'Groceries',
    productIcon: groceries,
  },
  {
    id: 400,
    productName: 'Home & Office',
    productIcon: homeoffice,
  },
  {
    id: 530,
    productName: 'Computers',
    productIcon: computers,
    link: `/category/${'electronics'}`,
  },
  {
    id: 630,
    productName: 'Power',
    productIcon: power,
    link: `/category/${'electronics'}`,
  },
  {
    id: 730,
    productName: 'Electronics',
    productIcon: electronics,
    link: `/category/${'electronics'}`,
  },
  {
    id: 82,
    productName: 'Phones',
    productIcon: phones,
    link: `/category/${'electronics'}`,
  },
  {
    id: 90,
    productName: 'Kids',
    productIcon: kids,
    link: `/category${'/toys'}`,
  },
  {
    id: 100,
    productName: 'Sports Items',
    productIcon: sports,
    link: `/category/${'toys'}`,
  },
  {
    id: 110,
    productName: 'Health & Beauty',
    productIcon: healthbeauty,
    link: `/category/${'beauty'}`,
  },
  {
    id: 120,
    productName: 'Mobile Accessories',
    productIcon: mobileaccessories,
    link: `/category/${'electronics'}`,
  },
  {
    id: 130,
    productName: 'Toys & Games',
    productIcon: toysgames,
    link: `/category/${'toys'}`,
  },
];

export const singleProductCategories = [
  {
    id: 105,
    productName: 'Phones',
    link: `/category/${'electronics'}`,
  },

  {
    id: 530,
    productName: 'Computers',
    link: `/category/${'electronics'}`,
  },
  {
    id: 201,
    productName: 'TV',
    link: `/category/${'electronics'}`,
  },

  {
    id: 630,
    productName: 'Home Audio & Theater',
    link: `/category/${'electronics'}`,
  },
  {
    id: 730,
    productName: 'Video Games',
    link: `/category/${'electronics'}`,
  },
  {
    id: 82,
    productName: 'Gadgets',
    link: `/category/${'electronics'}`,
  },
  {
    id: 90,
    productName: 'Home Appliances',
    link: `/category${'/electronics'}`,
  },
  {
    id: 100,
    productName: 'Accessories',
    link: `/category/${'toys'}`,
  },
];

export const productAds = [
  {
    id: 1,
    name: "Valentine's Special",
    image: valentineAd,
  },
  {
    id: 2,
    name: "Valentine's Special",
    image: valentineAd,
  },
  {
    id: 3,
    name: "Valentine's Special",
    image: valentineAd,
  },
];

export const heroCards = [
  {
    id: 1,
    image: happyMan,
    alt: 'An Image of a lady sitting on the sofa while wearing hoodie',
  },
  {
    id: 2,
    image: girInHoodie,
    alt: 'An Image of a lady sitting on the sofa while wearing hoodie',
    text: 'Shop the latest',
    textDetails: 'Electronics, fashion, home essentials, grocery all here.',
    shoppingCart: shoppingCart,
  },
  {
    id: 3,
    image: YellowBox,
    alt: 'An Image of a lady sitting on the sofa while wearing hoodie',
  },
];

export const products = [
  {
    id: '1',
    name: 'Samsung Galaxy Note 10 Plus 256gb/12gb Single Sim - Purple',
    brand: 'Samsung',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/248528/pexels-photo-248528.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '207000',
    discountPrice: '225000',
    discountPercentage: '23',
    ratings: '3.5',
    noOfProductSold: '20',
    slug: 'samsung-galaxy-note-10-plus',
    paymentOptions: [
      {
        type: 'daily',
        label: 'Daily',
        days: 30,
        dailyPayment: 6900,
        totalPrice: 207000,
      },
      {
        type: 'weekly',
        label: 'Weekly',
        weeks: 6,
        weeklyPayment: 34500,
        totalPrice: 207000,
      },
      {
        type: 'monthly',
        label: 'Monthly',
        months: 3,
        monthlyPayment: 69000,
        totalPrice: 207000,
      },
      {
        type: 'upfront',
        label: 'Pay in full',
        amount: 207000,
      },
    ],
  },
  {
    id: '2',
    name: 'iPhone 14 Pro Max',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/1275229/pexels-photo-1275229.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '500000',
    ratings: '4.8',
    noOfProductSold: '50',
    slug: 'iphone-14-pro-max',
    paymentOptions: [
      {
        type: 'daily',
        label: 'Daily',
        days: 30,
        dailyPayment: 1369.86,
        totalPrice: 500000,
      },
      {
        type: 'weekly',
        label: 'Weekly',
        weeks: 4,
        weeklyPayment: 9615.38,
        totalPrice: 500000,
      },
      {
        type: 'monthly',
        label: 'Monthly',
        months: 6,
        upfrontPayment: 150000,
        monthlyPayment: 150000,
        totalPrice: 500000,
      },
      {
        type: 'upfront',
        label: 'Pay in full',
        amount: 500000,
        totalPrice: 500000,
      },
    ],
  },
  {
    id: '3',
    name: 'Google Pixel 7 Pro',
    brand: 'Google',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/163100/pexels-photo-163100.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '300000',
    discountPrice: '320000',
    ratings: '4.6',
    noOfProductSold: '30',
    slug: 'google-pixel-7-pro',
    paymentOptions: [
      { type: 'upfront', amount: 300000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 90000,
        monthlyPayment: 70000,
        totalPrice: 300000,
      },
    ],
  },
  {
    id: '4',
    name: 'OnePlus 10 Pro',
    brand: 'OnePlus',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '280000',
    discountPrice: '10',
    ratings: '4.7',
    noOfProductSold: '25',
    slug: 'oneplus-10-pro',
    paymentOptions: [
      { type: 'upfront', amount: 280000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 84000,
        monthlyPayment: 65333.33,
        totalPrice: 280000,
      },
    ],
  },
  {
    id: '5',
    name: 'Xiaomi Mi 12',
    brand: 'Xiaomi',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '200000',
    discountPrice: '220000',
    ratings: '4.4',
    noOfProductSold: '22',
    slug: 'xiaomi-mi-12',
    paymentOptions: [
      { type: 'upfront', amount: 200000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 60000,
        monthlyPayment: 46666.67,
        totalPrice: 200000,
      },
    ],
  },
  {
    id: '6',
    name: 'Samsung Galaxy S22 Ultra',
    brand: 'Samsung',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '400000',
    discountPrice: '420000',
    ratings: '4.9',
    noOfProductSold: '40',
    slug: 'samsung-galaxy-s22-ultra',
    paymentOptions: [
      { type: 'upfront', amount: 400000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 120000,
        monthlyPayment: 93333.33,
        totalPrice: 400000,
      },
    ],
  },
  {
    id: '7',
    name: 'iPhone SE (2022)',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '150000',
    discountPrice: '170000',
    ratings: '4.3',
    noOfProductSold: '18',
    slug: 'iphone-se-2022',
    paymentOptions: [
      { type: 'upfront', amount: 150000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 45000,
        monthlyPayment: 35000,
        totalPrice: 150000,
      },
    ],
  },
  {
    id: '8',
    name: 'Google Pixel 6a',
    brand: 'Google',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/821652/pexels-photo-821652.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '180000',
    discountPrice: '200000',
    ratings: '4.5',
    noOfProductSold: '28',
    slug: 'google-pixel-6a',
    paymentOptions: [
      { type: 'upfront', amount: 180000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 54000,
        monthlyPayment: 42000,
        totalPrice: 180000,
      },
    ],
  },
  {
    id: '9',
    name: 'OnePlus Nord 2',
    brand: 'OnePlus',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '220000',
    discountPrice: '240000',
    ratings: '4.6',
    noOfProductSold: '35',
    slug: 'oneplus-nord-2',
    paymentOptions: [
      { type: 'upfront', amount: 220000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 66000,
        monthlyPayment: 51333.33,
        totalPrice: 220000,
      },
    ],
  },
  {
    id: '10',
    name: 'Xiaomi Redmi Note 11',
    brand: 'Xiaomi',
    category: 'Electronics',
    subcategory: 'Mobile Phones',
    image:
      'https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '120000',
    discountPrice: '140000',
    ratings: '4.2',
    noOfProductSold: '20',
    slug: 'xiaomi-redmi-note-11',
    paymentOptions: [
      { type: 'upfront', amount: 120000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 36000,
        monthlyPayment: 28000,
        totalPrice: 120000,
      },
    ],
  },
  {
    id: '11',
    name: 'Samsung 55-inch 4K Smart TV',
    brand: 'Samsung',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/333984/pexels-photo-333984.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '300000',
    discountPrice: '320000',
    ratings: '4.7',
    noOfProductSold: '15',
    slug: 'samsung-55-inch-4k-smart-tv',
    paymentOptions: [
      { type: 'upfront', amount: 300000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 90000,
        monthlyPayment: 70000,
        totalPrice: 300000,
      },
    ],
  },
  {
    id: '12',
    name: 'LG 65-inch OLED Evo TV',
    brand: 'LG',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '500000',
    discountPrice: '550000',
    ratings: '4.9',
    noOfProductSold: '20',
    slug: 'lg-65-inch-oled-evo-tv',
    paymentOptions: [
      { type: 'upfront', amount: 500000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 150000,
        monthlyPayment: 116666.67,
        totalPrice: 500000,
      },
    ],
  },
  {
    id: '13',
    name: 'Sony Bravia XR 77-inch OLED TV',
    brand: 'Sony',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/5552789/pexels-photo-5552789.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '750000',
    discountPrice: '800000',
    ratings: '4.8',
    noOfProductSold: '10',
    slug: 'sony-bravia-xr-77-inch-oled-tv',
    paymentOptions: [
      { type: 'upfront', amount: 750000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 225000,
        monthlyPayment: 175000,
        totalPrice: 750000,
      },
    ],
  },
  {
    id: '14',
    name: 'TCL 50-inch QLED TV',
    brand: 'TCL',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/704555/pexels-photo-704555.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '280000',
    discountPrice: '300000',
    ratings: '4.6',
    noOfProductSold: '30',
    slug: 'tcl-50-inch-qled-tv',
    paymentOptions: [
      { type: 'upfront', amount: 280000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 84000,
        monthlyPayment: 65333.33,
        totalPrice: 280000,
      },
    ],
  },
  {
    id: '15',
    name: 'Hisense 58-inch ULED TV',
    brand: 'Hisense',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/333984/pexels-photo-333984.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '350000',
    discountPrice: '370000',
    ratings: '4.5',
    noOfProductSold: '25',
    slug: 'hisense-58-inch-uled-tv',
    paymentOptions: [
      { type: 'upfront', amount: 350000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 105000,
        monthlyPayment: 81666.67,
        totalPrice: 350000,
      },
    ],
  },
  {
    id: '16',
    name: 'Panasonic 65-inch 4K LED TV',
    brand: 'Panasonic',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/7234737/pexels-photo-7234737.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '450000',
    discountPrice: '480000',
    ratings: '4.7',
    noOfProductSold: '18',
    slug: 'panasonic-65-inch-4k-led-tv',
    paymentOptions: [
      { type: 'upfront', amount: 450000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 135000,
        monthlyPayment: 105000,
        totalPrice: 450000,
      },
    ],
  },
  {
    id: '17',
    name: 'Sharp 70-inch Aquos TV',
    brand: 'Sharp',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/3769747/pexels-photo-3769747.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '600000',
    discountPrice: '650000',
    ratings: '4.8',
    noOfProductSold: '12',
    slug: 'sharp-70-inch-aquos-tv',
    paymentOptions: [
      { type: 'upfront', amount: 600000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 180000,
        monthlyPayment: 140000,
        totalPrice: 600000,
      },
    ],
  },
  {
    id: '18',
    name: 'Vizio 55-inch M-Series TV',
    brand: 'Vizio',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/333984/pexels-photo-333984.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '320000',
    discountPrice: '350000',
    ratings: '4.6',
    noOfProductSold: '22',
    slug: 'vizio-55-inch-m-series-tv',
    paymentOptions: [
      { type: 'upfront', amount: 320000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 96000,
        monthlyPayment: 74666.67,
        totalPrice: 320000,
      },
    ],
  },
  {
    id: '19',
    name: 'Philips 50-inch Ambilight TV',
    brand: 'Philips',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/1201996/pexels-photo-1201996.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '280000',
    discountPrice: '310000',
    ratings: '4.5',
    noOfProductSold: '14',
    slug: 'philips-50-inch-ambilight-tv',
    paymentOptions: [
      { type: 'upfront', amount: 280000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 84000,
        monthlyPayment: 65333.33,
        totalPrice: 280000,
      },
    ],
  },
  {
    id: '20',
    name: 'Toshiba 55-inch Fire TV',
    brand: 'Toshiba',
    category: 'Electronics',
    subcategory: 'TV & Video',
    image:
      'https://images.pexels.com/photos/704555/pexels-photo-704555.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '310000',
    discountPrice: '340000',
    ratings: '4.6',
    noOfProductSold: '19',
    slug: 'toshiba-55-inch-fire-tv',
    paymentOptions: [
      { type: 'upfront', amount: 310000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 93000,
        monthlyPayment: 72333.33,
        totalPrice: 310000,
      },
    ],
  },
  {
    id: '30',
    name: 'LG Double Door Refrigerator',
    brand: 'LG',
    category: 'Electronics',
    subcategory: 'Fridge & Freezer',
    image:
      'https://images.pexels.com/photos/731082/pexels-photo-731082.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '400000',
    discountPrice: '420000',
    ratings: '4.6',
    noOfProductSold: '12',
    slug: 'lg-double-door-refrigerator',
    paymentOptions: [
      { type: 'upfront', amount: 400000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 120000,
        monthlyPayment: 93333.33,
        totalPrice: 400000,
      },
    ],
  },
  {
    id: '31',
    name: 'Samsung Smart TV 55 inch',
    brand: 'Samsung',
    category: 'Electronics',
    subcategory: 'Television',
    image:
      'https://images.pexels.com/photos/333984/pexels-photo-333984.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '500000',
    discountPrice: '520000',
    ratings: '4.8',
    noOfProductSold: '20',
    slug: 'samsung-smart-tv-55-inch',
    paymentOptions: [
      { type: 'upfront', amount: 500000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 150000,
        monthlyPayment: 116666.67,
        totalPrice: 500000,
      },
    ],
  },
  {
    id: '32',
    name: 'Sony Home Theater System',
    brand: 'Sony',
    category: 'Electronics',
    subcategory: 'Audio',
    image:
      'https://images.pexels.com/photos/1649771/pexels-photo-1649771.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '150000',
    discountPrice: '170000',
    ratings: '4.5',
    noOfProductSold: '8',
    slug: 'sony-home-theater-system',
    paymentOptions: [
      { type: 'upfront', amount: 150000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 45000,
        monthlyPayment: 35000,
        totalPrice: 150000,
      },
    ],
  },
  {
    id: '33',
    name: 'Apple MacBook Pro 16-inch',
    brand: 'Apple',
    category: 'Electronics',
    subcategory: 'Laptop',
    image:
      'https://images.pexels.com/photos/303383/pexels-photo-303383.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '1500000',
    discountPrice: '1550000',
    ratings: '4.9',
    noOfProductSold: '30',
    slug: 'apple-macbook-pro-16-inch',
    paymentOptions: [
      { type: 'upfront', amount: 1500000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 450000,
        monthlyPayment: 350000,
        totalPrice: 1500000,
      },
    ],
  },
  {
    id: '34',
    name: 'HP Envy x360 Laptop',
    brand: 'HP',
    category: 'Electronics',
    subcategory: 'Laptop',
    image:
      'https://images.pexels.com/photos/7974/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=500',
    price: '700000',
    discountPrice: '750000',
    ratings: '4.7',
    noOfProductSold: '15',
    slug: 'hp-envy-x360-laptop',
    paymentOptions: [
      { type: 'upfront', amount: 700000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 210000,
        monthlyPayment: 163333.33,
        totalPrice: 700000,
      },
    ],
  },
  {
    id: '35',
    name: 'Bose Noise Cancelling Headphones',
    brand: 'Bose',
    category: 'Electronics',
    subcategory: 'Headphones',
    image:
      'https://images.pexels.com/photos/205926/pexels-photo-205926.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '180000',
    discountPrice: '200000',
    ratings: '4.8',
    noOfProductSold: '22',
    slug: 'bose-noise-cancelling-headphones',
    paymentOptions: [
      { type: 'upfront', amount: 180000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 54000,
        monthlyPayment: 42000,
        totalPrice: 180000,
      },
    ],
  },
  {
    id: '36',
    name: 'Canon EOS R6 Camera',
    brand: 'Canon',
    category: 'Electronics',
    subcategory: 'Camera',
    image:
      'https://images.pexels.com/photos/51383/pexels-photo-51383.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '900000',
    discountPrice: '950000',
    ratings: '4.7',
    noOfProductSold: '10',
    slug: 'canon-eos-r6-camera',
    paymentOptions: [
      { type: 'upfront', amount: 900000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 270000,
        monthlyPayment: 210000,
        totalPrice: 900000,
      },
    ],
  },
  {
    id: '37',
    name: 'Dell UltraSharp Monitor',
    brand: 'Dell',
    category: 'Electronics',
    subcategory: 'Monitor',
    image:
      'https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '300000',
    discountPrice: '320000',
    ratings: '4.6',
    noOfProductSold: '18',
    slug: 'dell-ultrasharp-monitor',
    paymentOptions: [
      { type: 'upfront', amount: 300000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 90000,
        monthlyPayment: 70000,
        totalPrice: 300000,
      },
    ],
  },
  {
    id: '38',
    name: 'Nike Air Max Sneakers',
    brand: 'Nike',
    category: 'Fashion',
    subcategory: 'Shoes',
    image:
      'https://images.pexels.com/photos/1240892/pexels-photo-1240892.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '80000',
    discountPrice: '90000',
    ratings: '4.8',
    noOfProductSold: '40',
    slug: 'nike-air-max-sneakers',
    paymentOptions: [
      { type: 'upfront', amount: 80000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 24000,
        monthlyPayment: 18666.67,
        totalPrice: 80000,
      },
    ],
  },
  {
    id: '39',
    name: 'Rolex Submariner Watch',
    brand: 'Rolex',
    category: 'Fashion',
    subcategory: 'Watches',
    image:
      'https://images.pexels.com/photos/277319/pexels-photo-277319.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '2000000',
    discountPrice: '2100000',
    ratings: '4.9',
    noOfProductSold: '5',
    slug: 'rolex-submariner-watch',
    paymentOptions: [
      { type: 'upfront', amount: 2000000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 600000,
        monthlyPayment: 466666.67,
        totalPrice: 2000000,
      },
    ],
  },
  {
    id: '41',
    name: 'LG Double Door Refrigerator',
    brand: 'LG',
    category: 'Electronics',
    subcategory: 'Refrigerators',
    image:
      'https://images.pexels.com/photos/731082/pexels-photo-731082.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '400000',
    discountPrice: '420000',
    ratings: '4.6',
    noOfProductSold: '12',
    slug: 'lg-double-door-refrigerator',
    paymentOptions: [
      { type: 'upfront', amount: 400000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 120000,
        monthlyPayment: 93333.33,
        totalPrice: 400000,
      },
    ],
  },
  {
    id: '42',
    name: 'Samsung Microwave Oven',
    brand: 'Samsung',
    category: 'Electronics',
    subcategory: 'Microwaves',
    image:
      'https://images.pexels.com/photos/534119/pexels-photo-534119.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '120000',
    discountPrice: '135000',
    ratings: '4.7',
    noOfProductSold: '25',
    slug: 'samsung-microwave-oven',
    paymentOptions: [
      { type: 'upfront', amount: 120000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 36000,
        monthlyPayment: 28000,
        totalPrice: 120000,
      },
    ],
  },
  {
    id: '43',
    name: 'Panasonic 4-Burner Gas Cooker',
    brand: 'Panasonic',
    category: 'Electronics',
    subcategory: 'Cookers',
    image:
      'https://images.pexels.com/photos/279135/pexels-photo-279135.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '150000',
    discountPrice: '165000',
    ratings: '4.5',
    noOfProductSold: '18',
    slug: 'panasonic-4-burner-gas-cooker',
    paymentOptions: [
      { type: 'upfront', amount: 150000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 45000,
        monthlyPayment: 35000,
        totalPrice: 150000,
      },
    ],
  },
  {
    id: '44',
    name: 'Philips Air Fryer',
    brand: 'Philips',
    category: 'Electronics',
    subcategory: 'Air Fryers',
    image:
      'https://images.pexels.com/photos/4397892/pexels-photo-4397892.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '85000',
    discountPrice: '95000',
    ratings: '4.8',
    noOfProductSold: '30',
    slug: 'philips-air-fryer',
    paymentOptions: [
      { type: 'upfront', amount: 85000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 25500,
        monthlyPayment: 19833.33,
        totalPrice: 85000,
      },
    ],
  },
  {
    id: '45',
    name: 'Bosch Electric Kettle',
    brand: 'Bosch',
    category: 'Electronics',
    subcategory: 'Kettles',
    image:
      'https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '25000',
    discountPrice: '30000',
    ratings: '4.4',
    noOfProductSold: '40',
    slug: 'bosch-electric-kettle',
    paymentOptions: [
      { type: 'upfront', amount: 25000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 7500,
        monthlyPayment: 5833.33,
        totalPrice: 25000,
      },
    ],
  },
  {
    id: '46',
    name: 'Nutribullet Blender',
    brand: 'Nutribullet',
    category: 'Electronics',
    subcategory: 'Blenders',
    image:
      'https://images.pexels.com/photos/128865/pexels-photo-128865.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '45000',
    discountPrice: '50000',
    ratings: '4.6',
    noOfProductSold: '22',
    slug: 'nutribullet-blender',
    paymentOptions: [
      { type: 'upfront', amount: 45000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 13500,
        monthlyPayment: 10500,
        totalPrice: 45000,
      },
    ],
  },
  {
    id: '47',
    name: 'Kenwood Food Processor',
    brand: 'Kenwood',
    category: 'Electronics',
    subcategory: 'Food Processors',
    image:
      'https://images.pexels.com/photos/4397892/pexels-photo-4397892.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '65000',
    discountPrice: '70000',
    ratings: '4.7',
    noOfProductSold: '15',
    slug: 'kenwood-food-processor',
    paymentOptions: [
      { type: 'upfront', amount: 65000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 19500,
        monthlyPayment: 15166.67,
        totalPrice: 65000,
      },
    ],
  },
  {
    id: '48',
    name: 'Hisense Chest Freezer',
    brand: 'Hisense',
    category: 'Electronics',
    subcategory: 'Freezers',
    image:
      'https://images.pexels.com/photos/731082/pexels-photo-731082.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '210000',
    discountPrice: '225000',
    ratings: '4.5',
    noOfProductSold: '10',
    slug: 'hisense-chest-freezer',
    paymentOptions: [
      { type: 'upfront', amount: 210000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 63000,
        monthlyPayment: 49000,
        totalPrice: 210000,
      },
    ],
  },
  {
    id: '49',
    name: 'Prestige Toaster',
    brand: 'Prestige',
    category: 'Electronics',
    subcategory: 'Toasters',
    image:
      'https://images.pexels.com/photos/534119/pexels-photo-534119.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '20000',
    discountPrice: '25000',
    ratings: '4.3',
    noOfProductSold: '35',
    slug: 'prestige-toaster',
    paymentOptions: [
      { type: 'upfront', amount: 20000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 6000,
        monthlyPayment: 4666.67,
        totalPrice: 20000,
      },
    ],
  },
  {
    id: '50',
    name: 'LG Dishwasher',
    brand: 'LG',
    category: 'Kitchen Appliances',
    subcategory: 'Dishwashers',
    image:
      'https://images.pexels.com/photos/6237918/pexels-photo-6237918.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '350000',
    discountPrice: '370000',
    ratings: '4.7',
    noOfProductSold: '8',
    slug: 'lg-dishwasher',
    paymentOptions: [
      { type: 'upfront', amount: 350000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 105000,
        monthlyPayment: 81666.67,
        totalPrice: 350000,
      },
    ],
  },
  {
    id: '60',
    name: 'MAC Matte Lipstick',
    brand: 'Maybelline',
    category: 'beauty',
    subcategory: 'Makeup',
    image:
      'https://images.pexels.com/photos/1029896/pexels-photo-1029896.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '8000',
    discountPrice: '9500',
    ratings: '4.7',
    noOfProductSold: '120',
    slug: 'maybelline-fit-me-foundation',
    paymentOptions: [
      { type: 'upfront', amount: 8000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 2400,
        monthlyPayment: 1866.67,
        totalPrice: 8000,
      },
    ],
  },
  {
    id: '61',
    name: 'Maybelline Fit Me Foundation',
    brand: 'MAC',
    category: 'beauty',
    subcategory: 'Makeup',
    image:
      'https://images.pexels.com/photos/3373745/pexels-photo-3373745.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '12000',
    discountPrice: '13500',
    ratings: '4.8',
    noOfProductSold: '150',
    slug: 'mac-matte-lipstick',
    paymentOptions: [
      { type: 'upfront', amount: 12000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 3600,
        monthlyPayment: 2800,
        totalPrice: 12000,
      },
    ],
  },
  {
    id: '62',
    name: 'Nivea Body Lotion',
    brand: 'Nivea',
    category: 'beauty',
    subcategory: 'Skincare',
    image:
      'https://images.pexels.com/photos/4465124/pexels-photo-4465124.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '3500',
    discountPrice: '4000',
    ratings: '4.6',
    noOfProductSold: '200',
    slug: 'nivea-body-lotion',
    paymentOptions: [
      { type: 'upfront', amount: 3500 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 1050,
        monthlyPayment: 816.67,
        totalPrice: 3500,
      },
    ],
  },
  {
    id: '63',
    name: 'CeraVe Foaming Facial Cleanser',
    brand: 'CeraVe',
    category: 'beauty',
    subcategory: 'Skincare',
    image:
      'https://images.pexels.com/photos/4465835/pexels-photo-4465835.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '6000',
    discountPrice: '6800',
    ratings: '4.9',
    noOfProductSold: '180',
    slug: 'cerave-foaming-facial-cleanser',
    paymentOptions: [
      { type: 'upfront', amount: 6000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 1800,
        monthlyPayment: 1400,
        totalPrice: 6000,
      },
    ],
  },
  {
    id: '64',
    name: "L'Oreal Paris Shampoo",
    brand: "L'Oreal Paris",
    category: 'beauty',
    subcategory: 'Haircare',
    image:
      'https://images.pexels.com/photos/4465831/pexels-photo-4465831.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '2800',
    discountPrice: '3200',
    ratings: '4.5',
    noOfProductSold: '250',
    slug: 'loreal-paris-shampoo',
    paymentOptions: [
      { type: 'upfront', amount: 2800 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 840,
        monthlyPayment: 653.33,
        totalPrice: 2800,
      },
    ],
  },
  {
    id: '65',
    name: 'Tresemme Conditioner',
    brand: 'Tresemme',
    category: 'beauty',
    subcategory: 'Haircare',
    image:
      'https://images.pexels.com/photos/4465832/pexels-photo-4465832.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '3200',
    discountPrice: '3600',
    ratings: '4.7',
    noOfProductSold: '230',
    slug: 'tresemme-conditioner',
    paymentOptions: [
      { type: 'upfront', amount: 3200 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 960,
        monthlyPayment: 746.67,
        totalPrice: 3200,
      },
    ],
  },
  {
    id: '66',
    name: 'Zara Women Summer Dress',
    brand: 'Zara',
    category: 'beauty',
    subcategory: 'Clothing',
    image:
      'https://images.pexels.com/photos/974911/pexels-photo-974911.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '15000',
    discountPrice: '17000',
    ratings: '4.5',
    noOfProductSold: '95',
    slug: 'zara-women-summer-dress',
    paymentOptions: [
      { type: 'upfront', amount: 15000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 4500,
        monthlyPayment: 3500,
        totalPrice: 15000,
      },
    ],
  },
  {
    id: '67',
    name: "Nike Men's Running Shoes",
    brand: 'Nike',
    category: 'beauty',
    subcategory: 'Clothing',
    image:
      'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '25000',
    discountPrice: '28000',
    ratings: '4.8',
    noOfProductSold: '130',
    slug: 'nike-mens-running-shoes',
    paymentOptions: [
      { type: 'upfront', amount: 25000 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 7500,
        monthlyPayment: 5833.33,
        totalPrice: 25000,
      },
    ],
  },
  {
    id: '68',
    name: 'Rolex Gold Watch',
    brand: 'Rolex',
    category: 'beauty',
    subcategory: 'Accessories',
    image:
      'https://images.pexels.com/photos/277319/pexels-photo-277319.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '2500',
    discountPrice: '2700',
    ratings: '4.9',
    noOfProductSold: '15',
    slug: 'rolex-gold-watch',
    paymentOptions: [
      { type: 'upfront', amount: 2500 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 750,
        monthlyPayment: 583.33,
        totalPrice: 2500,
      },
    ],
  },
  {
    id: '69',
    name: 'Ray-Ban Aviator Sunglasses',
    brand: 'Ray-Ban',
    category: 'beauty',
    subcategory: 'Accessories',
    image:
      'https://images.pexels.com/photos/343720/pexels-photo-343720.jpeg?auto=compress&cs=tinysrgb&w=500',
    price: '2500',
    discountPrice: '2700',
    ratings: '4.9',
    noOfProductSold: '15',
    slug: 'ray-ban-aviator-sunglasses',
    paymentOptions: [
      { type: 'upfront', amount: 2500 },
      {
        type: 'monthly',
        months: 3,
        upfrontPayment: 750,
        monthlyPayment: 583.33,
        totalPrice: 2500,
      },
    ],
  },
];

export const popularProducts = [
  {
    id: 1,
    image: '/images/computers&tablets.svg',
    name: 'TV, Cell phone, Laptops',
    category: 'Electronics',
    link: `/category/${'electronics'}`,
  },
  {
    id: 2,
    image: '/images/makeup-kits.svg',
    name: 'Makeup,  hair, body lotion  ',
    category: 'Health&Beauty',
    link: `/category/${'beauty'}`,
  },
  {
    id: 3,
    image: '/images/flower-basket.svg',
    name: 'Rice, Yam, Chicken',
    category: 'Groceries',
    link: 'href/home/groceries',
  },
];

export const popularProductsSort = [
  {
    id: 1,
    image: '/images/american-man.svg',
    name: 'Shirts, jeans, tees and more',
    category: 'Men',
    link: `/category/${'beauty'}`,
  },
  {
    id: 2,
    image: '/images/fashionable-young-woman.svg',
    name: 'Dresses, jewelries, hair and more ',
    category: 'Women',
    link: `/category/${'beauty'}`,
  },
  {
    id: 3,
    image: '/images/american-kid.svg',
    name: 'Sofa, decor, appliance and more',
    category: 'Kids',
    link: `/category/${'toys'}`,
  },
  {
    id: 4,
    image: '/images/living-room.svg',
    name: 'Sofa, decor, appliance and more',
    category: 'Home',
    link: './',
  },
];

export const menuFooter = [
  {
    title: 'Fair',
    links: [
      { name: 'About us', link: '/about-us' },
      { name: 'Privacy policy', link: '/privacy-policy' },
      { name: 'Feedback', link: '/feedback' },
      { name: 'Press', link: '/press' },
      { name: 'Legal', link: '/legal' },
      { name: 'Careers', link: '/careers' },
    ],
  },
  {
    title: 'Shop',
    links: [
      { name: 'Categories', link: '/categories' },
      { name: 'Deals', link: '/deals' },
      { name: 'Trending', link: '/trending' },
      { name: 'Buying guide', link: '/buying-guide' },
      { name: 'Gift card', link: '/gift-card' },
      { name: 'Create an account', link: '/create-account' },
    ],
  },
  {
    title: 'Sell',
    links: [
      { name: 'Start selling', link: '/start-selling' },
      { name: 'How to sell', link: '/how-to-sell' },
      { name: 'Getting paid', link: '/getting-paid' },
      { name: 'Vendor app', link: '/vendor-app' },
    ],
  },
  {
    title: 'Support',
    links: [
      { name: 'Contact us', link: '/contact-us' },
      { name: 'Help center', link: '/help-center' },
      { name: 'Market place guidelines', link: '/marketplace-guidelines' },
      { name: 'Buyer protection', link: '/buyer-protection' },
      { name: 'Seller protection', link: '/seller-protection' },
      { name: 'Refunds and returns', link: '/refunds-returns' },
    ],
  },
];

export const states = [
  { name: 'Abia' },
  { name: 'Adamawa' },
  { name: 'Akwa Ibom' },
  { name: 'Anambra' },
  { name: 'Bauchi' },
  { name: 'Bayelsa' },
  { name: 'Benue' },
  { name: 'Borno' },
  { name: 'Cross River' },
  { name: 'Delta' },
  { name: 'Ebonyi' },
  { name: 'Edo' },
  { name: 'Ekiti' },
  { name: 'Enugu' },
  { name: 'Gombe' },
  { name: 'Imo' },
  { name: 'Jigawa' },
  { name: 'Kaduna' },
  { name: 'Kano' },
  { name: 'Katsina' },
  { name: 'Kebbi' },
  { name: 'Kogi' },
  { name: 'Kwara' },
  { name: 'Lagos' },
  { name: 'Nasarawa' },
  { name: 'Niger' },
  { name: 'Ogun' },
  { name: 'Ondo' },
  { name: 'Osun' },
  { name: 'Oyo' },
  { name: 'Plateau' },
  { name: 'Rivers' },
  { name: 'Sokoto' },
  { name: 'Taraba' },
  { name: 'Yobe' },
  { name: 'Zamfara' },
  { name: 'Federal Capital Territory (FCT)' },
];
